-- sql/schema.sql
CREATE TABLE IF NOT EXISTS shipments (
    id INTEGER PRIMARY KEY,
    date_of_shipment DATE,
    year INT,
    month INT,
    quarter TEXT,
    hsn_code TEXT,
    hsn_description TEXT,
    goods_description TEXT,
    supplier_name TEXT,
    supplier_address TEXT,
    quantity NUMERIC,
    unit TEXT,
    unit_standardized TEXT,
    unit_price_inr NUMERIC,
    total_value_inr NUMERIC,
    duty_paid_inr NUMERIC,
    grand_total_inr NUMERIC,
    landed_cost_per_unit NUMERIC,
    model_name TEXT,
    model_number TEXT,
    capacity_spec TEXT,
    material_type TEXT,
    embedded_quantity INT,
    unit_price_usd NUMERIC,
    category TEXT,
    sub_category TEXT
);
